### PR TITLE
fix: add auth buttons to the login view only

### LINKED ISSUE #8: SyntaxError: Unexpected token < in JSON at position 0
When I’m connected to the panel, for example at /panel/site, I can see the following error in the browser console:

```
SyntaxError: Unexpected token < in JSON at position 0
```

This is due to the code at https://github.com/blankogmbh/kirby-oauth/blob/master/index.js#L40-L41 being executed. The condition at https://github.com/blankogmbh/kirby-oauth/blob/master/index.js#L6 returning true (I guess that’s not the desired behavior, this code should be executed only on the panel login page).

Anyway, since the user is already connected, the async request to `/oauth/settings` returns a 302 that redirects to /panel, which itself return the panel home page as HTML resulting in the error above: the HTML response cannot be parsed as JSON.

I think the condition on line 6 should be adapter to be executed only on the login page or at least not when the user is already logged in.

Kirby 3.2.3
Kirby oauth 1.0.0

### PR DESCRIPTION
**Pull request by LeBenLeBen**
fixes #8

### CODE REVIEW

**Comment by thathoff** [comment]
Thanks! 👍

**Comment by thathoff** [comment]
Just merged this into a release branch to test it on some of our installations. It seems that the check does not always work and the login buttons are not added to the form. I think this is a race condition, when you start your request with /panel (without the login at the end) and the panel redirects to /panel/login. Then in some cases our script is faster and only sees /panel in the url. I think a better solution will be to don’t redirect every plugin request to the panel when the user is logged in (https://github.com/blankogmbh/kirby-oauth/blob/master/src/Controller.php#L25). I’ll try to implement this today or tomorrow.

**Comment by LeBenLeBen** [comment]
Damn, I was expecting something like this… I guess the best solution would be to create a custom login view as mentioned in #5

**Comment by thathoff** [comment]
Yes sure! But for a quick fix i think moving the mentioned line(s) into `Controller::index()` would at lease eliminate the console error in the panel…

**Pull request merged**
